[build]
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
