[build]
  functions = "netlify/functions"
  command = "npm run build:upload-sourcemaps"

[build.environment]
  NODE_VERSION = "22"
  BUGSNAG_API_KEY = "05fe04ebc304ae56dcdc160914d06c1c"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
